# .github/workflows/build.yml - Buildozer Docker İmajı Güncellemesi
name: Android APK Build (Kivy Docker)

on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: 1. Kaynak Kodu Çıkar
      uses: actions/checkout@v4

    - name: 2. Buildozer Docker Ortamını Kur ve Çalıştır
      # GÜNCELLENMİŞ İMAJ: Python 3.10 (en yaygın kullanılan stabil sürüm) etiketini kullanıyoruz.
      uses: docker://kivy/buildozer:python3-10
      
      with:
        # Buildozer'a gönderilecek komut
        args: buildozer android debug

    - name: 3. Oluşturulan APK'yı Bul
      id: find_apk
      run: |
        APK_PATH=$(find bin -name "*.apk" | head -n 1)
        if [ -z "$APK_PATH" ]; then
          echo "HATA: bin klasöründe APK dosyası bulunamadı."
          exit 1
        fi
        echo "apk_path=$APK_PATH" >> $GITHUB_OUTPUT

    - name: 4. APK'yı GitHub Artifacts'a Yükle
      uses: actions/upload-artifact@v4
      with:
        name: sevgili-oyunu-apk
        path: ${{ steps.find_apk.outputs.apk_path }}
        retention-days: 7
