name: Kotlin Android Build (Gradle - Son Deneme)

on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: 1. Kaynak Kodu Çıkar
      uses: actions/checkout@v4

    - name: 2. Java 17 Kurulumu (Kotlin/Android için gerekli)
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: 3. Android SDK ve Gradle Cache'i Kur
      uses: actions/cache@v4
      with:
        path: ~/.android/build-cache
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle*') }}

    # 4. Doğrulama Adımı (gradle/wrapper-validation-action) KALDIRILDI
    
    - name: 4. Gradle Wrapper JAR'ı İndir ve Kur (Force)
      # JAR dosyasını indirmek için zorlayıcı betik
      run: |
        if [ ! -f gradle/wrapper/gradle-wrapper.jar ]; then
          mkdir -p gradle/wrapper
          echo "JAR dosyası yok, indiriliyor..."
          curl -L 'https://repo.maven.apache.org/maven2/org/gradle/wrapper/gradle-wrapper/8.4/gradle-wrapper-8.4.jar' -o gradle/wrapper/gradle-wrapper.jar
        fi

    - name: 5. Android SDK ve NDK'yı Ayarla
      uses: android-actions/setup-android@v2

    - name: 6. Gradle Wrapper'a Yürütme İzni Ver (Tekrar)
      run: chmod +x gradlew

    - name: 7. Android/Gradle ile Derle
      run: ./gradlew :android:assembleDebug
      
    - name: 8. Oluşturulan APK'yı Yükle
      uses: actions/upload-artifact@v4
      with:
        name: kotlin-android-apk
        path: android/build/outputs/apk/debug/android-debug.apk
        retention-days: 7
