name: Kotlin Android Build (Son Deneme)

on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: 1. Kaynak Kodu Çıkar
      uses: actions/checkout@v4

    - name: 2. Java 17 Kurulumu (Kotlin/Android için gerekli)
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: 3. Android SDK ve Gradle Cache'i Kur
      uses: actions/cache@v4
      with:
        path: ~/.android/build-cache
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle*') }}

    # JAR indirme adımı kaldırıldı, artık projede var.
    
    - name: 4. Gradle Wrapper'a Yürütme İzni Ver
      run: chmod +x gradlew

    - name: 5. Android SDK ve NDK'yı Ayarla
      uses: android-actions/setup-android@v2

    - name: 6. Android/Gradle ile Derle (Şimdi Çalışmalı)
      # JAR dosyası proje içinde olduğu için, bu adım artık çalışmalı.
      run: ./gradlew :android:assembleDebug
      
    - name: 7. Oluşturulan APK'yı Yükle
      uses: actions/upload-artifact@v4
      with:
        name: kotlin-android-apk
        path: android/build/outputs/apk/debug/android-debug.apk
        retention-days: 7
